# Get low size alpine image for dotnet runtime
FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine

# Make directory for storing the files
RUN mkdir -p /app/hdns && mkdir -p /usr/share/hdns

# Set work directory
WORKDIR /app

# Copy the application files & the service file for reference (dont' copy the configuration files as it might overwrite the user defined files)
COPY ./ /app/hdns

# We also need to remove the special characters in our file.
# stream editor , inplace, s/substitute \r with // (carriage return with nothing)
RUN sed -i 's/\r//' /app/hdns/entrypoint.sh &&  sed -i 's/\r//' /app/hdns/hlog &&  sed -i 's/\r//' /app/hdns/hdns.service

# Set environment variables
ENV env_hdns_logdir="/var/log/hlog"
ENV env_hdns_cfgdir="/usr/share/hdns"

#Define volumes (not actual mounting.. just defining)
VOLUME /usr/share/hdns
VOLUME /var/log/hlog

# Define entrypoint
ENTRYPOINT ["/bin/sh","/app/hdns/entrypoint.sh"]